typography_spectrum: 0.9908090785611421
color:
  brandStrength: 0.26400836650282145
  lightness: 0.329042307799682
  saturation: 0.6733508121687919
  rhythmicContrast: 0.4079033671878278
  brandColors:
    - '#F8F7F3'
    - '#F750C4'
    - '#03AF95'
    - '#033131'
    - '#E90B18'
layout_spectrum: 0.5777447121217847
name: Liberty Fitting Service Ltd
navigation:
  - name: Dundee Kitchens
    url: 'http://www.libertyfittingservice.co.uk/'
    type: external
description: Excellence as Standard
